import Head from 'next/head'
import { FC } from "react"

export const Headers: FC = () => {
    return (
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    );
  };